### ISSUE TITLE
update fail

### ISSUE THREAD

**Issue by colinallen** [inpho/vsm#131]
```
% vsm version
1.0b58-0-ge1c16e3
% vsm update
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/vsm", line 9, in <module>
    load_entry_point('topicexplorer==1.0b58', 'console_scripts', 'vsm')()
  File "/Users/colin/corpora/Byron/Docs/topicexplorer/topicexplorer/__main__.py", line 178, in main
    benchmark(update.main)(args)
TypeError: main() takes no arguments (1 given)
'''

**Comment by colinallen** [comment]
Also may be relevant:

pip install concludes with:
  Running setup.py develop for topicexplorer
Successfully installed topicexplorer-1.0b54

then vsm version shows b58 as above.
