### ISSUE TITLE
Key error running on c_allen txt corpus

### ISSUE THREAD

**Issue by colinallen** [inpho/vsm#132]
during vsm init c_allen -- KeyError: u'in\x00\x00\x00\x00\x00\x00\x00\x00'
with 1.0b58-5-g2b5fb98

```
Building corpus from c_allen
Detected 0 folders and 95 files in c_allen
Constructing directory corpus, each file is a document
100%|##########################################################################|
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/vsm", line 9, in <module>
    load_entry_point('topicexplorer==1.0b58', 'console_scripts', 'vsm')()
  File "/Users/colin/bin/topicexplorer/topicexplorer/__main__.py", line 142, in main
    args.config_file = benchmark(init.main)(args)
  File "/Users/colin/bin/topicexplorer/topicexplorer/init.py", line 153, in main
    stop_freq=5, decode=args.decode)
  File "/Users/colin/bin/topicexplorer/topicexplorer/init.py", line 94, in build_corpus
    ignore=ignore, decode=decode)
  File "/Users/colin/anaconda/lib/python2.7/site-packages/vsm/extensions/corpusbuilders/corpusbuilders.py", line 659, in dir_corpus
    c = Corpus(words, context_data=data, context_types=names)
  File "/Users/colin/anaconda/lib/python2.7/site-packages/vsm/corpus/base.py", line 467, in __init__
    for word in self.corpus],
KeyError: u'in\x00\x00\x00\x00\x00\x00\x00\x00'
'''

**Comment by JaimieMurdock** [comment]
I had this issue with the UN-corpus as well, going to investigate in depth on Saturday. Have a quick fix, but this shouldn't be happening in the first place.

**Comment by JaimieMurdock** [comment]
The issue has something to do with a unicode codec not being detected correctly.
