### ISSUE TITLE
error in vsn.corpus.remove_empty() on py3k migration

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/vsm#149]
```
/home/jaimie/anaconda3/lib/python3.6/site-packages/vsm-0.4.0b9-py3.6-linux-x86_64.egg/vsm/corpus/base.py:241: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1228584
  self.context_data[j] = self.context_data[j][indices]
Traceback (most recent call last):
  File "/home/jaimie/anaconda3/bin/topicexplorer", line 11, in <module>
    load_entry_point('topicexplorer', 'console_scripts', 'topicexplorer')()
  File "/home/jaimie/workspace/topic-explorer/topicexplorer/__main__.py", line 206, in main
    args.config_file = benchmark(init.main)(args)
  File "/home/jaimie/workspace/topic-explorer/topicexplorer/init.py", line 266, in main
    c = htrc_features.create_corpus(ids)
  File "/home/jaimie/workspace/topic-explorer/topicexplorer/extensions/htrc_features.py", line 61, in create_corpus
    c = corpus_fromlist(corpus, context_type='book')
  File "/home/jaimie/anaconda3/lib/python3.6/site-packages/vsm-0.4.0b9-py3.6-linux-x86_64.egg/vsm/extensions/corpusbuilders/corpusbuilders.py", line 174, in corpus_fromlist
    context_types=[context_type])
  File "/home/jaimie/anaconda3/lib/python3.6/site-packages/vsm-0.4.0b9-py3.6-linux-x86_64.egg/vsm/corpus/base.py", line 508, in __init__
    self.remove_empty()
  File "/home/jaimie/anaconda3/lib/python3.6/site-packages/vsm-0.4.0b9-py3.6-linux-x86_64.egg/vsm/corpus/base.py", line 241, in remove_empty
    self.context_data[j] = self.context_data[j][indices]
IndexError: index 0 is out of bounds for axis 1 with size 0
```

**Comment by JaimieMurdock** [comment]
Python 3:
```
100%|################################################################################################################################################################################################################################|
['book']
Removing empty 0 [('idx', '<i8'), ('book_label', 'O')]
<class 'numpy.ndarray'> (0,)
Traceback (most recent call last):
```

Python 2:
```
100%|##########################################################################|
['book']
Removing empty 0 [('idx', '<i8'), ('book_label', 'O')]
<type 'numpy.ndarray'> (10,)
Saving corpus as volumes.test.txt-freq5.npz
```

**Comment by JaimieMurdock** [comment]
Wow. The issue was that `map` returns an iterator in python 3, as opposed to a list in python 2.
