### ISSUE TITLE
rc1 setup.py issue

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/vsm#151]
```
Collecting vsm==0.4.0rc1 (from topicexplorer)
  Downloading vsm-0.4.0rc1.tar.gz (372kB)
    100% |████████████████████████████████| 378kB 10.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3z9uuanp/vsm/setup.py", line 62, in <module>
        ext_modules = cythonize(extensions),
      File "/opt/applications/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 799, in cythonize
        aliases=aliases)
      File "/opt/applications/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 691, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/opt/applications/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 107, in nonempty
        raise ValueError(error_msg)
    ValueError: 'vsm/model/_cgs_update.pyx' doesn't match any files
```

**Comment by JaimieMurdock** [comment]
Need to create `MANIFEST.in` with `include vsm/model/_cgs_update.pyx`. remove `cpp` and `c` files from sdist
